# Generated by Django 2.2.5 on 2020-09-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.TextField(default='default')),
                ('fname', models.TextField(default='default')),
                ('fbody', models.BinaryField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='default')),
                ('file_list', models.TextField(default='{}')),
                ('df_pklfname', models.TextField(default='default')),
                ('filter_text', models.TextField(default='{}')),
                ('feature_list', models.TextField(default='{}')),
                ('value_list', models.TextField(default='{}')),
                ('val_mtx', models.TextField(default='{}')),
                ('margins', models.TextField(default='{}')),
                ('feature', models.TextField(default='{}')),
                ('space_col', models.TextField(default='')),
                ('time_col', models.TextField(default='')),
                ('margins_tab', models.TextField(default='{}')),
                ('copula_tab', models.TextField(default='{}')),
                ('stage', models.IntegerField(default=0)),
            ],
        ),
    ]
