# Generated by Django 2.2.5 on 2021-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpscopmodelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conc_mtx',
            field=models.TextField(default='{}'),
        ),
    ]
